#!/usr/bin/env node

/**
 * Complete setup script for local development environment
 * This creates all necessary .env.local files
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

console.log('🚀 Setting up local development environment...\n');

// Step 1: Setup Frontend
console.log('📝 Step 1: Setting up frontend environment...');
const clientEnvPath = join(projectRoot, 'client', '.env.local');
const clientTemplate = `# Local Development Configuration
# This file is automatically generated. Edit as needed.

VITE_API_URL=http://localhost:4000/api
VITE_FRONTEND_URL=http://localhost:5173
`;

if (existsSync(clientEnvPath)) {
  console.log('   ⚠️  client/.env.local already exists. Skipping...');
} else {
  writeFileSync(clientEnvPath, clientTemplate, 'utf8');
  console.log('   ✅ Created client/.env.local');
}

// Step 2: Setup Backend
console.log('\n📝 Step 2: Setting up backend environment...');
const serverEnvPath = join(projectRoot, 'server', '.env.local');
const serverTemplate = `# Local Development Configuration
# This file is automatically generated. 
# ⚠️  IMPORTANT: Update database credentials below!

# Server Configuration
PORT=4000
NODE_ENV=development

# Frontend Configuration
FRONTEND_URL=http://localhost:5173
INVITE_BASE_URL=http://localhost:5173/invite

# Database Configuration (DEV Environment - Used for Local Development)
DB_HOST=dpg-d41rn4juibrs73flltn0-a.singapore-postgres.render.com
DB_PORT=5432
DB_NAME=investo_3mo3
DB_USER=investo_3mo3_user
DB_PASSWORD=8UExBu4D44YsoQOEtGa9PTw9do3XUQ5E
DB_SSL=true
DB_LOGGING=true

# Optional: Use direct connection string instead
# DATABASE_URL=postgres://postgres:password@localhost:5432/zerovaste
`;

if (existsSync(serverEnvPath)) {
  console.log('   ⚠️  server/.env.local already exists. Skipping...');
} else {
  writeFileSync(serverEnvPath, serverTemplate, 'utf8');
  console.log('   ✅ Created server/.env.local');
}

// Summary
console.log('\n✨ Setup Complete!\n');
console.log('📋 Summary:');
console.log('   ✅ client/.env.local - Created');
console.log('   ✅ server/.env.local - Created\n');

console.log('⚠️  IMPORTANT INFORMATION:\n');
console.log('✅ Database credentials are pre-configured for DEV environment');
console.log('   - Local development uses DEV database (configured in server/.env.local)');
console.log('   - Production uses PROD database (configured in Render dashboard)\n');

console.log('2. Start the backend server:');
console.log('   cd server');
console.log('   npm run dev\n');

console.log('3. Start the frontend (in a new terminal):');
console.log('   cd client');
console.log('   npm run dev\n');

console.log('📚 For more details, see docs/STEP_BY_STEP_SETUP.md\n');


